### ISSUE TITLE
URL rewriter plugin problem with base_url

### ISSUE THREAD

**Issue by ghost** [PHPFrame/PHPFrame#1]
The URL rewriter plugin appears to be rewriting urls relative to the current url and not the base url.

**Comment by chrismcband** [comment]
PHPFrame_URI dirname should be returning "/" even when the requested url is only the root url. Then the SessionRegistry should not need to append the "/" as all request cases should be correct. This is a special case where the app residing at the web root and a request using the exact base url has the url dirname being returned as "" when it should still be returning "/".

**Comment by lupomontero** [comment]
This issue is directly related to [Issue 3](http://github.com/PHPFrame/PHPFrame/issues/#issue/3) so lets continue that thread and close this one for now. I will add a reference in the other thread linking back here just in case.
