### ISSUE TITLE
JSONRenderer using php json encoding not rendering persistent object collections

### ISSUE THREAD

**Issue by chrismcband** [PHPFrame/PHPFrame#13]
JSONRenderer used with default options (php json set to true) does not render persistent object collections correctly. It just appears as an empty object, using php json set to false its fine.

Looking at the source it seems to be because the render() function is not checking for arrays or objects and so is not calling _renderObject or _renderArray.

**Comment by lupomontero** [comment]
This issue should have been fixed a while ago:
https://github.com/PHPFrame/PHPFrame/blob/master/src/PHPFrame/Document/JSONRenderer.php#L107

Closing for now...
