### ISSUE TITLE
ObjectRelationalToolbox createTable uses varchar(100) for all string fields

### ISSUE THREAD

**Issue by chrismcband** [PHPFrame/PHPFrame#15]
Creating a table using PHPFrame_ObjectRelationalToolbox uses varchar(100) for all string fields. Regardless of setting the max_length option of StringFilter. Also the default value appears to be ignored completely, due to this condition:
    if (!is_null($def_values[$key])
         && !$filter instanceof PHPFrame_StringFilter
    ) {
         $column->setDefault($def_values[$key]);
    }

**Comment by lupomontero** [comment]
Hi Chris,

That's is just the default column width for displaying results (in the shell for example). All VARCHAR columns have inherently the same maximum storage length of 64k. So it shouldn't matter whether the fields are created using varchar(100) or any other value in the parenthesis. I know this is a bit odd.

The effective maximum length of a VARCHAR in MySQL 5.0.3 and later is subject to the maximum row size (65,535 bytes, which is shared among all columns) and the character set used. 

This issue shouldn't be urgent for now but if you feel like fixing it please go ahead and I'll review the commit.

Best,

L

**Comment by chrismcband** [comment]
The number does affect the database though, varchar(100) will only allow 100 chars to be inserted. If you go over that you will get a warning 'data truncated' and your text will be cut off. Are you saying that it doesn't matter what value you use for varchar in that you do not actually save any space in the database? In which case we should just use a very big default value for varchar, but if it does save some space, we should use the max_length if specified, if not use 100 or something.

**Comment by lupomontero** [comment]
Ooops. I think I got confused with SQLite, where it really doesn't make any difference. But you are right, in MySQL data does get truncated.

Can you do the hack?

Cheers,

L

**Comment by chrismcband** [comment]
The hack is in, I added a length property to DatabaseColumn, ObjectRelationalToolbox will set the length property if max_length is set on the filter for varchar or char fields and MySQLDatabase will use the length property when creating the table.

**Comment by lupomontero** [comment]
Cool. I've checked the commit log and it looks great. I'll pull the changes to my fork on Monday... no coding for me tonight ;-)

Thanks,

L
