### ISSUE TITLE
Feature Request addScript

### ISSUE THREAD

**Issue by svnlto** [PHPFrame/PHPFrame#17]
We need a value we can set so the function knows whether the script goes into head oder footer.
wordpress's enqueue script function does that pretty well.

http://codex.wordpress.org/Function_Reference/wp_enqueue_script#Parameters

**Comment by lupomontero** [comment]
Argument "in_head" added to HTMLDocument::addScript() method. See http://github.com/PHPFrame/PHPFrame/commit/14ff009100533f0e26e476233c2fc9f7acfdd343

L
