### ISSUE TITLE
XMLRPCClient needs to be refactored to use latest framework API

### ISSUE THREAD

**Issue by lupomontero** [PHPFrame/PHPFrame#2]
We need to refactor, and actually slightly redesign the XML API for applications built on the framework.

**Comment by chrismcband** [comment]
Is there anything I can help with this? What were your ideas for refactoring? We kind of need to use xml rpc right now.

**Comment by lupomontero** [comment]
Hi Chris,

I'm not going to have the time to look at this issue today, but I will look at in detail over the weekend and get back to you on Monday with clear idea (and plan) of how the XMLRPCClient class should be refactored for the current version of the framework.

L

**Comment by lupomontero** [comment]
After the workshop on Monday I guess we can consider this issue close. Now we need to look at the cookie path problem and an elegant way to handle errors and exceptions for all clients. I will add issues for these.
