### ISSUE TITLE
CLI tool scaffold table regexp too strict

### ISSUE THREAD

**Issue by chrismcband** [PHPFrame/PHPFrame#22]
The regular expression used in the cli scaffold table action is too strict. It generally only works with models that have been generated using the cli tool. E.g. following won't be matched:
    class AccountProfile extends PHPFrame_PersistentObject 
        implements PHPFrame_RESTfulObject
    {

**Comment by lupomontero** [comment]
Is this fixed in https://github.com/PHPFrame/PHPFrame/commit/853c956338b0f57d8eb179adfe9fc74f887d3979 ?
L

**Comment by chrismcband** [comment]
Yes 20, 21 and 22 should be fixed, closing this one.
