### ISSUE TITLE
PHPFrame_PolymorphicPersistentObject type length

### ISSUE THREAD

**Issue by willvdmerwe** [PHPFrame/PHPFrame#24]
Minimum length for 'type' is 6 .. bit restrictive .. can't use 'note' .. or 'user' ... or any of those handy four-letter words. ..just a thought.

**Comment by lupomontero** [comment]
Hey will,

Lets just change it.
1. Get a fork
2. Change the relevant line in your fork: https://github.com/PHPFrame/PHPFrame/blob/master/src/PHPFrame/Mapper/PolymorphicPersistentObject.php#L43
3. Commit
4. Push to your fork
5. Send pull request on GitHub

Peace,

L

**Comment by willvdmerwe** [comment]
This is done .. opened pull request. (Reopened to post comment)
