### ISSUE TITLE
Cookie path is not being set correctly

### ISSUE THREAD

**Issue by lupomontero** [PHPFrame/PHPFrame#3]
Cookie path is not being set correctly probably because of rewritten URLs being parsed by PHPFrame_URI before the rewriter gets a chance to process the request URI.

**Comment by lupomontero** [comment]
See previous issue for reference: [Issue 1](http://github.com/PHPFrame/PHPFrame/issues/closed/#issue/1)

**Comment by lupomontero** [comment]
I've pushed a fix for this issue to the master branch, so please update your fork... 

I have also updated the release version to 0.0.21 and the latest successful build is now: [http://dist.phpframe.org/PHPFrame-0.0.21-build.70.tgz](http://dist.phpframe.org/PHPFrame-0.0.21-build.70.tgz)

The session (responsible for creating the cookie) doesn't get started until the application's dispatch() method. Since the session object is always referenced using PHPFrame_Applicaton::session() and the app knows the base url (regardless of rewriting rules) now we pass the base_url to the session class when instantiating. I think this does the trick.

Can you please confirm that this was the case?

L

**Comment by chrismcband** [comment]
I think it is working now. If I use just the base url, base url/index.php or base url/login it appears to work.
When I use it with /login/ the cookie path is /login/ but logging in still works, you just get another cookie with path /.
By the way, I noticed you deleted PHPFrame_RPCObject, we were using that interface in RPCRenderer to return the fields of the object that the user wants to send over xmlrpc. By default only the database fields will be sent, if the persistent object implemented the interface the RPCRenderer would use the fields obtained from getRPCFields(), which allows objects which are made up of sub-objects to be sent as one large composite object. Did you have another method planned for this sort of thing?

**Comment by lupomontero** [comment]
Chris,

I will close this issue for now and we can continue the main discussion in [Issue 7](http://github.com/PHPFrame/PHPFrame/issues/issue/7).
