### ISSUE TITLE
PersistentObject storage with optional array initialisation

### ISSUE THREAD

**Issue by chrismcband** [PHPFrame/PHPFrame#5]
If you create a Persistent object and initialise it using the options array and then store it, it will not be inserted as the PersistentObject superclass constructor marks it as being clean, even if it has been initialised with some data. Therefore you cannot create an object initialise it in the constructor and then store it.

**Comment by lupomontero** [comment]
A fix for this issue including unit tests to reproduce the bug have been pushed to the master branch...

Latest successful build is now: [http://dist.phpframe.org/PHPFrame-0.0.22-build.72.tgz](http://dist.phpframe.org/PHPFrame-0.0.22-build.72.tgz)
